### ISSUE TITLE
Convert @ABSTRACT annotations to `abstract` modifier

### ISSUE THREAD

**Issue by yjbanov** [angular/ts2dart#18]
This:

```
@ABSTRACT()
class Blah {}
```

Transpiles to this:

```
@ABSTRACT()
class Blah {}
```

But should be:

```
abstract class Blah {}
```

Methods and getters can also be abstract.

**Comment by kevmoo** [comment]
@chalin You can subscribe by clicking on the button on the right in the repo

**Comment by chalin** [comment]
Right, thanks. Actually, I am subscribed to the entire project, as well as to angular, source_gen.dart, etc. Hence, what I was actually doing is marking myself as someone who wants to participate in the resolution of this issue. As you know GitHub supports filtering based on participation; this is very useful. Maybe there should be a star feature for issues in GitHub. Sorry for the notification noise.

Anyhow, that being said, I investigated this issue and noticed that TS doesn't yet support annotations (since 1.5 isn't out), hence this cannot be implemented yet (at least not in any way that I can see).

**Comment by mprobst** [comment]
TS doesn't have abstract classes, but has interfaces. So the fix is to write:
```ts
interface Blah {}
```

Which we do translate to:
```dart
abstract class Blah{}
```
