### ISSUE TITLE
Change how we handle IMPLEMENTS

### ISSUE THREAD

**Issue by vsavkin** [angular/ts2dart#209]
Currently the following

```
@IMPLEMENTS(MyInterface)
class MyClass {}
```

will be translated into:
```
class MyClass implements MyInterface {}
```

This issue with this approach is that MyInterface cannot actually be an interface in TS. It has to be a class. I think we should change it into something like this:
 
```
@IMPLEMENTS<MyInterface>
class MyClass {}
```

So TS does not need MyInterface to be present at runtime.

**Comment by mprobst** [comment]
You mean so that *Dart* does not need `MyInterface` to be present at runtime?

Can't we just use TypeScript's native `implements`?

**Comment by mprobst** [comment]
For background, offline conversation clarified that the motivation behind this is mocking for tests. In Angular, it's apparently common to create a mock for a particular type by writing `@IMPLEMENTS(Service) class ServiceMock { someMethod(); /* but not otherMethod() */ }`, but leaving most methods out, i.e. only partially implementing.

Because TypeScript compiles away interfaces, they cannot be used in annotations like this. At the same time you cannot just write `class ServiceMock implements Service {}`, because it obviously doesn't and the compiler checks that (Dart gets around that using `noSuchMethod`).

Dart on the other hand must have an actual class that actually implements the required type, because checked mode assertions will fail if an object doesn't actually nominally extend a type.

I'm not sure if I'm more amazed or appalled by this creative abuse of the limitations of `@IMPLEMENTS` and the intersection of TypeScript and Dart.

The only way I can come up with to avoid this is having a `service_mock.ts` and a `service_mock.dart` and splitting the class definition - `service_mock.ts` would just use TypeScript's structural typing to mock, or a crazy cast, `service_mock.dart` would just have a `class ServiceMock extends Mock implements Service {}`, but not much more. Both files would have a `getServiceMock` method that returns the appropriate mock object, and maybe takes a mock control.

While that's a bit more code for the mocked files, I think that'd be much cleaner, and wouldn't abuse a completely unrelated mechanism. It'd also allow us to get rid of `@IMPLEMENTS` alltogether in the medium term.

**Comment by mprobst** [comment]
Closing this, please reopen if you don't agree @vsavkin.

**Comment by alexeagle** [comment]
In https://github.com/angular/angular/pull/3835 `@IMPLEMENTS` is being removed from angular. When that's in, we can remove the support from ts2dart
