### ISSUE TITLE
Facade converter only replace method invocations for methods

### ISSUE THREAD

**Issue by vicb** [angular/ts2dart#210]
When thinking again about `Map.delete()` (#205) I realized that `['a', 'b'].map(m.delete)` might not work.

However this issue is not applicable to `Map.delete` only, `['a', 'b'].map(m.has)` would not work either (`Error: main.ts:1:62: Untyped property access to "has" which could be a special ts2dart builtin. Please add type declarations to disambiguate.`)

There is an easy workaround `['a', 'b'].map((v) => m.has(v))`. Do we want to update and fix the first syntax ?

**Comment by mprobst** [comment]
Is `['a', 'b'].map(m.has)` actually correct? The call to `Map.has` wouldn't receive `m` as the `this` pointer, would it? I think the Dart semantics of closure-izing an instance method don't match JavaScript's here, though that problem is unrelated to recognizing the method.

We could actually have simple method renames implemented as property renames, so `someMap.has` would translate to `someMap.containsKey`, regardless of call or not. We already have the infrastructure for that for e.g. `Map.size` vs `.length`.

But you'd usually end up with code that doesn't quite work as you'd expect.

**Comment by vicb** [comment]
You're right, closing
