### ISSUE TITLE
Explicit `void` and `dynamic` return types

### ISSUE THREAD

**Issue by yjbanov** [angular/ts2dart#4]
We should transpile the following TypeScript:

```
foo() {}
bar():void {}
baz():any {}
```

To the following Dart:

```
void foo() {}
void bar() {}
baz() {}  // by convention in Dart this means return dynamic
```

**Comment by rkirov** [comment]
I disagree with the first one:
```foo() {}``` should be left as ```foo() {}```
In TS I am saying, 'let TS infer the return type of foo'. So the correct translation to dart should be 'let Dart infer the return type of foo'.

**Comment by chalin** [comment]
The rules for inferring the implicit return type of a function are not trivial; cf. Section 6.3, *Function Implementations* of the [TypeScript Language Specification, Version 1.4 (October, 2014)](http://www.typescriptlang.org/Content/TypeScript%20Language%20Specification.pdf):

-----
A function implementation without a return type annotation is said to be an implicitly typed function.
The return type of an implicitly typed function f is inferred from its function body as follows:
* If there are no return statements with expressions in f's function body, the inferred return type is
**Void**.
* Otherwise, if f's function body directly references f or references any implicitly typed functions
that through this same analysis reference f, the inferred return type is Any.
* Otherwise, if f is a contextually typed function expression (section 4.9.3), the inferred return type is
the union type (section 3.4) of the types of the return statement expressions in the function body,
ignoring return statements with no expressions.
* Otherwise, the inferred return type is the first of the types of the return statement expressions in
the function body that is a supertype (section 3.10.3) of each of the others, ignoring return
statements with no expressions. A compile-time error occurs if no return statement expression
has a type that is a supertype of each of the others.

-----
So, by the first bullet, `foo() {}` actually has an implicit return type of `void`. But do we want to **only** cover for the first bullet in the rules above and not the others? If we are catering to the needs of Angular2, then we should probably just make it a **convention in the Angular2 code base that all function return types are declared explicitly**.

**Comment by chalin** [comment]
IMHO, for sake of consistency, the third case
```
baz():any {...}
```
should be translated to
```dart
dynamic baz() {...}
```
If the TS developer explicitly marked the return type as `any`, then that effect should be propagated. 

Again, IMHO, explicitly marking a return type as "any" is documentation from the developer saying "this function can return anything (including nothing)" vs. "I haven't given any thought as to (or can be bothered to figure out) what type this function might return, so I'll let the compiler infer it". (My 2 cents)

**Comment by chalin** [comment]
In https://github.com/angular/angular/issues/491#issuecomment-82738585 @yjbanov wrote:

> In Angular 2 code if anything is returned at all it should have a return type. 

I agree that that is the most sound advice.

> Lack of type is assumed to be void as a matter of style.

That would be inadvisable. Whether we like it or not, I think that an expectation will arise that `ts2dart` will  preserve semantics (at least to some extent). Hence, I think that the rules of Section 6.3 of the TS spec (see above) should either be followed to the letter or, when not followed a gentle warning should be given: e.g., something vaguely like "You have not explicitly given the return type of function f, we will assume it is Dart type X, though this might not correspond to the implicit type mandated by the TS spec".

From https://github.com/angular/angular/issues/491#issuecomment-73352012:
> It is not the transpiler's job to infer and add types.

That is a simple and acceptable design decision.

**Comment by mprobst** [comment]
+1 to @chalin and @rkirov, I think these should transpile as:

```
foo() {} // unspecified, infer
void bar() {}  // specified void
dynamic baz() {}  // specified dynamic
```

As is, ts2dart does exactly that, AFAICT, so I'm closing this.

**Comment by yjbanov** [comment]
For the record, SGTM
