### ISSUE TITLE
Multiple variable initializers in for loop (`for (var x, y = 0; x; x++) { .. }`)

### ISSUE THREAD

**Issue by mprobst** [angular/ts2dart#83]

**Comment by chalin** [comment]
In Dart (and Java, C, C#, etc) all variables in a (for-loop) variable declaration list must have the same type. Since we are doing syntax directed translation in ts2dart, we cannot reliably determine if distinct variables are declared with the same type or not. Hence I suggest that either we start working from a fully resloved AST or we impose the following restrictions:

* A variable declaration list with a single variable can be explicitly typed.
* When more than one variable is in the list, all must be implicitly typed.

Since I assume that we will not start working with resolved ASTs: @mprobst, @alexeagle do you agree with the restrictions given above?

**Comment by alexeagle** [comment]
I'm not sure what's involved to get the resolved AST, symbol table, etc. I
imagine we should have easy access to them through the language services
API.
Martin and I will be in Redmond visiting the TypeScript team on Thursday.
I'll add this to our notes for discussion with them.

In general it's okay if our transpiler accepts a subset of the language,
but those will be sharp edges for compatibility problems so we should be
careful when we do it.

**Comment by chalin** [comment]
> I'll add this to our notes for discussion with them.

Good, thanks.

> but those will be sharp edges for compatibility problems so we should be
careful when we do it.

I agree.

**Comment by mprobst** [comment]
I think as long as we can give a clear error message, we can live with only
supporting homogeneously typed var decl lists.

Martin

Patrice Chalin <notifications@github.com> schrieb am Mo., 23. März 2015
20:07:
